name: clubhouse

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, closed, labeled]

jobs:
  clubhouse:
    runs-on: ubuntu-latest
    steps:
      - uses: singingwolfboy/create-linked-clubhouse-story@v1.8
        if: contains(github.event.pull_request.body, '[ch-new]') || contains(github.event.pull_request.labels.*.name, 'new clubhouse story')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          clubhouse-token: ${{ secrets.CLUBHOUSE_TOKEN }}
          project-name: Explore
          opened-state-name: In Development
          merged-state-name: Completed
          closed-state-name: Won't fix
          ignored-users: geminihlswadmin
          user-map: |
            {
              "rpiaggio": "5f4a944d-faa8-48d6-8611-f565df2715d5",
              "swalker": "5dc4137c-a307-4be9-b530-4516dc2bf0bf",
              "toddburnside": "5f493c15-019c-453f-8413-c08ec65675d9",
              "tpolecat": "5f49319b-41f4-43c4-a303-9025445831e0"
            }
