name: Debug

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test CI override
        env: 
          CI: false
        run: echo $CI
